export const experience = [
  {
    position: "DevOps Automation QA Co-op",
    shortPosition: "DevOps Co-op",
    company: "Verisk Extreme Events Solutions",
    location: "Boston, MA",
    category: "Work Experience",
    image: "/verisk.png",
    date: "Jan 2025 - Present",
    linkText: "verisk.com",
    linkURL: "https://www.verisk.com/company/newsroom/tags/extreme-event-solutions/",
    bullets: [
      "Developed and executed automated test scripts to enhance QA coverage using C# and Python.",
      "Collaborated with developers and product managers in an Agile environment to improve software quality.",
      "Worked to implement random and customizable realistic data generation for testing purposes.",
      "Contributed to the development of an internal testing tool, moving from on premise to cloud-based solutions, by building out a storage solution and RestAPIs.",
    ],
    showMore: true,
  },
  {
    position: "Software Developer",
    company: "Generate",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/generate.svg",
    date: "Sept 2024 - Present",
    linkText: "generatenu.com",
    linkURL: "https://generatenu.com/",
    bullets: [
      "Collaborated with developers and designers to build a music rating application and a carbon accounting platform for real-world clients",
      "Implemented Figma mockups using React, TypeScript, and Tailwind, creating an aesthetic, intuitive UI",
      "Developed a RESTful API using go, enabling seamless communication between the frontend and backend",
      "Integrated third-party APIs to enhance functionality, including user spotify authentication and history and transactional expense data",
    ],
    showMore: true,
  },
  {
    position: "CS3200 Database Design TA",
    shortPosition: "Database Design TA",
    company: "Khoury College of Computer Sciences",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/khoury.png",
    date: "Sept 2023 - Present",
    linkText: "catalog.northeastern.edu",
    linkURL: "https://catalog.northeastern.edu/course-descriptions/cs/",
    bullets: [
      "Hosted 4+ Office Hours each week to provide guidance and clarify difficult content to 550+ students",
      "Graded tests and homework efficiently and provided constructive feedback to students to help improve their skills",
      "Collaborated with 15+ other TA's in weekly meetings and office hours to determine the best approach for helping students and develop assignments and solutions",
      "Implemented Relational Algebra, SQL, and noSQL in Datagrip and MySQLWorkbench.",
      "Worked to develop challenging homework assignments.",
    ],
    showMore: true,
  },
  {
    position: "Student Organization Approvals Board Member",
    shortPosition: "SOAB Member",
    company: "Northeastern Student Government Association",
    location: "Boston, MA",
    category: "Campus Experience",
    image: "/SGA.png",
    date: "Jan 2024 - Present",
    linkText: "northeasternsga.com",
    linkURL: "https://www.northeasternsga.com",
    bullets: [
      "Reviewed and approved new student organization applications, ensuring compliance with university policies and procedures",
      "Carefully evaluated 100+ tentative student organizations, carefully evaluating their missions, constitutions, and potential contributions to our campus community",
    ],
    showMore: false,
  },
  {
    position: "Risk Assurance Data and Systems Co-op",
    shortPosition: "Data and Systems Co-op",
    company: "TJX Companies",
    location: "Marlboro, MA",
    category: "Work Experience",
    image: "/tjx.png",
    date: "Jan 2024 - June 2024",
    linkText: "tjx.com",
    linkURL: "https://www.tjx.com",
    bullets: [
      "Data engineering and analysis across multiple projects and problem areas using Snowflake, Excel, and Power Query",
      "Automate Manual processed to processes to save 8+ hours per week using Power Automate and Sharepoint",
    ],
    showMore: false,
  },
  {
    position: "Computer Science and Mathematics Student",
    shortPosition: "CS + Math Student",
    company: "Northeastern University",
    location: "Boston, MA",
    category: "Academics",
    image: "/northeastern.png",
    date: "Sep 2022 - Present",
    linkText: "northeastern.edu",
    linkURL: "https://www.northeastern.edu/",
    bullets: [
      "Pursuing a BS in Computer Science and Biology",
      "Khoury Dean's List, GPA 3.8/4.0",
      "Courses: Software Engineering, Algorithms and Data, Object-Oriented Design, Artificial Intelligence, Machine Learning and Data Mining, Database Design, Fundamentals of Computer Science I & II, Discrete Structures, Probability and Statistics, Number Theory, Linear Albegra, and more",
    ],
    showMore: false,
  },
];